### ISSUE TITLE
Using pi-puck 3D model with e-puck

### ISSUE THREAD

**Issue by jharwell** [allsey87/argos3-srocs#22]
The e-puck here: https://github.com/demiurge-project/argos3-epuck has a light sensor, but the pi-puck in this repo doesn't, and I need an ARGoS robot with a 3D model and a light sensor for the project I'm working on. What would I need to do to use the dynamics3D model for the pi-puck with the e-puck in the demiurge repo ?

**Comment by allsey87** [comment]
Hi @jharwell, by the light sensors, do you mean the 8 sensors around the base of the e-puck? Do you have a rough idea how you would want the readings to work? For example, should obstacles between the sensor and a light entity (i.e., a `<light />` in ARGoS) reduce the illumination?

I don't maintain [demiurge-project/argos3-epuck](https://github.com/demiurge-project/argos3-epuck) and I have my doubts as to whether it still works with the latest version of ARGoS, so beyond adapting the physics model there are plenty of other issues you may run into if you take this route.

The mid-term plan (i.e., in the coming months) is to migrate most of the plugins from this repository into the main repository. So I would recommend trying to use the pi-puck model from this repository with the latest master of [ilpincy/argos3](https://github.com/ilpincy/argos3).

**Comment by jharwell** [comment]
Yes I think so ? I just need a light sensor that behaves like the one on the ARGoS footbot for basic phototaxis, with all of the same behaviors. I would use the footbot model directly, but it currently has no 3D dynamics model :-(.

**Comment by allsey87** [comment]
To be honest, I don't know how the footbot's light sensors worked. I have implemented the [light sensors on the BuilderBot](https://github.com/allsey87/argos3-srocs/blob/master/src/plugins/robots/builderbot/simulator/builderbot_rangefinders_default_sensor.cpp#L140) robot, perhaps you could use that?

**Comment by allsey87** [comment]
I am going to close this issue for now since it doesn't identify a concrete problem with this code base. Feel free to open a new issue if there is a specific change to the code that you would like or a bug that you would like to see to fixed.
