### ISSUE TITLE
Drone rotate problem

### ISSUE THREAD

**Issue by freedomcondor** [allsey87/argos3-srocs#25]
This is a very old bug in the drone flight system, and it seems to be still there.
Every time I rotate a drone (press ctrl and turn middle button of the mouse),
or I simply declare the drone with an non-zero orientation : <body position=“1,0,0” orientation=“30,0,0"/>,
the drone seems to get confused of its home position and fly in circles.

In the following case, one drone is initialized with orientation "30,0,0", and the other "0,0,0". The second one is able to fly straight but the first one isn't.

https://user-images.githubusercontent.com/32301005/116264851-e8e36f00-a77a-11eb-8e24-1bec27fae36a.mp4

The test code is attached:
[test.zip](https://github.com/allsey87/argos3-srocs/files/6385566/test.zip)

**Comment by sinanOguz** [comment]
@allsey87 fixed.

**Comment by allsey87** [comment]
Fixed in 9f044ad5edafccf403659c9502d383e40e685d75
